**MACHINE LEARNING MODELS FOR EDUCATION CATEGORY**<br>
MULTICLASS CLASSIFICATION ML ALGORTHIMS IMPLEMENTED:-


1.   DECISION TREE
2.   SVM
3.   GAUSIAN BAYES
4.   K-NN

BEST ACCURACY MODEL: -<BR>
SVM (C=10,KERNEL=LINEAR)

In [ ]:
#importing the libraries
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix,accuracy_score

In [ ]:
#reading dataset
dataset=pd.read_csv('Education.csv')

In [ ]:
dataset.head()

College Tier  Course  Marks%  Intership  Credit Score Rating
0             1       1      91          6           401     AA
1             1       1      88          6           398     AA
2             1       1      89          5           389     AA
3             1       1      77          6           387     AA
4             1       1      95          4           385     AA

In [ ]:
#declaring and assigning values to dependent and indepedent variables
X = dataset.iloc[:,0:4].values
y = dataset.iloc[:,5].values

In [ ]:
#X Head
X[0:10,:]

array([[ 1,  1, 91,  6],
       [ 1,  1, 88,  6],
       [ 1,  1, 89,  5],
       [ 1,  1, 77,  6],
       [ 1,  1, 95,  4],
       [ 1,  1, 60,  6],
       [ 1,  2, 83,  6],
       [ 1,  2, 90,  5],
       [ 1,  1, 75,  4],
       [ 2,  1, 85,  6]])

In [ ]:
y

array(['AA', 'AA', 'AA', 'AA', 'AA', 'AA', 'AA', 'AA', 'AA', 'AA', 'AA',
       'AA', 'AA', 'AA', 'AA', 'AA', 'AA', 'AA', 'AA', 'AA', 'AA', 'AA',
       'AA', 'AA', 'AA', 'AA', 'AA', 'AA', 'AA', 'AA', 'AA', 'AA', 'AA',
       'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
       'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
       'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
       'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
       'A', 'A', 'A', 'A', 'A', 'A', 'BB', 'BB', 'BB', 'BB', 'BB', 'BB',
       'BB', 'BB', 'BB', 'BB', 'BB', 'BB', 'BB', 'BB', 'BB', 'BB', 'BB',
       'BB', 'BB', 'BB', 'BB', 'BB', 'BB', 'BB', 'BB', 'BB', 'BB', 'BB',
       'BB', 'BB', 'BB', 'BB', 'BB', 'BB', 'BB', 'BB', 'BB', 'BB', 'BB',
       'BB', 'BB', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B'], dtype=object

In [ ]:
#spilting into training and testing dataset
#70% is training dataset and 30% is testing dataset
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.3,shuffle=True)


In [ ]:
# training a DescisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier
dtree_model = DecisionTreeClassifier(criterion='entropy').fit(X_train, y_train)
dtree_predictions = dtree_model.predict(X_test)

In [ ]:
# creating a confusion matrix
dtree_cm = confusion_matrix(y_test, dtree_predictions)
dtree_cm

array([[12,  2,  0,  1],
       [ 1,  9,  0,  0],
       [ 1,  0, 10,  0],
       [ 6,  0,  0,  7]])

In [ ]:
#decision tree accuracy
dtree_accuracy = accuracy_score(dtree_predictions,y_test)
dtree_accuracy

0.7755102040816326

In [ ]:
# training a KNN classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1).fit(X_train, y_train)
knn_predictions = knn.predict(X_test)

In [ ]:
# creating a confusion matrix 
knn_cm = confusion_matrix(y_test, knn_predictions)
knn_cm

array([[6, 2, 0, 7],
       [2, 8, 0, 0],
       [0, 0, 7, 4],
       [3, 1, 4, 5]])

In [ ]:
# accuracy on X_test
KNN_accuracy = knn.score(X_test, y_test)
KNN_accuracy

0.5306122448979592

In [ ]:
# training naive bayes
# training a Naive Bayes classifier
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB().fit(X_train, y_train)
gnb_predictions = gnb.predict(X_test)

In [ ]:
# accuracy on X_test
gnb_accuracy = gnb.score(X_test, y_test)

In [ ]:
# creating a gnb confusion matrix
gnb_cm = confusion_matrix(y_test, gnb_predictions)
gnb_cm

array([[14,  0,  0,  1],
       [ 3,  7,  0,  0],
       [ 0,  0, 10,  1],
       [ 1,  0,  1, 11]])

In [ ]:
# training a linear SVM classifier
from sklearn.svm import SVC
svm_model_linear = SVC(kernel = 'linear', C = 10).fit(X_train, y_train)
svm_predictions = svm_model_linear.predict(X_test)

In [ ]:
# model accuracy for X_test  
svm_accuracy = svm_model_linear.score(X_test, y_test)
svm_accuracy

0.9591836734693877

In [ ]:
# creating a confusion matrix
svm_cm = confusion_matrix(y_test, svm_predictions)
svm_cm

array([[14,  1,  0,  0],
       [ 0, 10,  0,  0],
       [ 0,  0, 10,  1],
       [ 0,  0,  0, 13]])

In [ ]:
#Hyperparameter Tuning        
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
              {'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': [0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09]},
              {'C': [1, 10, 100, 1000], 'kernel': ['sigmoid'], 'gamma': [0.1,0.01,0.001,0.0001]}] 
grid_search = GridSearchCV(estimator = SVC(),
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
best_accuracy

0.9651515151515152

In [ ]:
#Best parameters after SVM Hyperparameter Tuning
best_parameters

{'C': 100, 'kernel': 'linear'}

In [ ]:
#SVM User prediction for Employment
college=4
course=1
marks=57
internship=6
var1 = np.array([[college,course,marks,internship]])
user_prediction= svm_model_linear.predict(var1)
print(user_prediction)

['A']
